### PR TITLE
Add support for Meteor.

### PR DESCRIPTION
**Pull request by arunoda**
Fixes: #1

### CODE REVIEW

**Comment by ffxsam** [comment]
Is it documented somewhere on how to address Meteor package imports breaking Storybook? Can we stub/mock these somehow? I do have an older install of Storybook, should I just uninstall it and use the new `getstorybook` process?

**Comment by arunoda** [comment]
That part is not there yet. May be we can create a new issue here. 

The docs will be available on our new getstorybook.io domain by next week.

**Comment by lnmunhoz** [comment]
@arunoda Are the docs available?

**Comment by caoer** [comment]
@arunoda is it solved? I'm still seeing Meteor imports errors.

**Comment by caoer** [comment]
@arunoda it will be great if Meteor example can have some code related to Meteor. talking about files under: https://github.com/kadirahq/getstorybook/tree/master/generators/METEOR

**Pull request merged**
